plugins {
    id 'java'
    id 'org.jetbrains.intellij' version '1.17.4'
}

version '1.4.4'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.fathzer:javaluator:3.0.3'
    testImplementation group: 'junit', name: 'junit', version: '4.13.2'
}

// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
    version = '2023.1'
    updateSinceUntilBuild = false
}

patchPluginXml {
    changeNotes = """
      <ul>
        <li>Extended syntax to to support placeholder # and \$</li>
        <li>support of hexadecimal values with prefix 0x</li>
      </ul>
      """
}
